Copy-Item "..\visualfsharp\artifacts\bin\fcs\Release\netstandard2.0\FSharp.Compiler.Service.dll" -Destination "ReSharper.FSharp\src\FSharp.Common\bin\Debug\net461\"
Copy-Item "..\visualfsharp\artifacts\bin\fcs\Release\netstandard2.0\FSharp.Compiler.Service.dll" -Destination "ReSharper.FSharp\src\FSharp.ProjectModelBase\bin\Debug\net461\"
Copy-Item "..\visualfsharp\artifacts\bin\fcs\Release\netstandard2.0\FSharp.Compiler.Service.dll" -Destination "ReSharper.FSharp\src\FSharp.Psi\bin\Debug\net461\"
Copy-Item "..\visualfsharp\artifacts\bin\fcs\Release\netstandard2.0\FSharp.Compiler.Service.dll" -Destination "ReSharper.FSharp\src\FSharp.Psi.Features\bin\Debug\net461\"
Write-Host "0"